she_codes_news/news/urls.py
from django.urls import path
from . import views

app_name = 'news'

urlpatterns = [
    path('', views.IndexView.as_view(), name='index'),
    path('<int:pk>/', views.StoryView.as_view(), name='story'),
    path('add-story/', views.AddStoryView.as_view(), name='newStory'),
    path('search/', views.search_results, name='search_results'),
]

she_codes_news/she_codes_news/urls.py
from django.contrib import admin
from django.urls import include, path

from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    path('news/', include('news.urls')),
    path('admin/', admin.site.urls),
    path('users/', include('users.urls')),
    path('users/', include('django.contrib.auth.urls')),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

she_codes_news/users/urls.py
# users/urls.py
from django.urls import path
from .views import CreateAccountView, ChangeAccountView
from users.views import ResetPasswordView
from django.contrib.auth import views as auth_views
from . import views


app_name ='users'

urlpatterns = [
    path('create-account/', CreateAccountView.as_view(), name='createAccount'),
    path('change-account/', ChangeAccountView.as_view(), name='changeAccount'),
    path('password-reset/', ResetPasswordView.as_view(), name='password_reset'),
    path('password-reset-confirm/<uidb64>/<token>/',
        auth_views.PasswordResetConfirmView.as_view(template_name='users/password_reset_confirm.html'),
        name='password_reset_confirm'),
    path('password-reset-complete/',
        auth_views.PasswordResetCompleteView.as_view(template_name='users/password_reset_complete.html'),
        name='password_reset_complete'),
    path('profile/', views.profile_view, name='userProfile'),
]

she_codes_news/users/models.py
from django.contrib.auth.models import AbstractUser
from django.db import models


class CustomUser(AbstractUser):
    pass

def __str__(self):
    return self.username


class UserProfile(models.Model):
    user = models.OneToOneField('CustomUser', on_delete=models.CASCADE)
    bio = models.TextField(blank=True)
    profile_picture = models.FileField(upload_to='profile_pics/', blank=True, null=True)
    
    def __str__(self):
        return self.user.username

she_codes_news/users/forms.py
# users/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm, UserChangeForm
from .models import CustomUser


class CustomUserCreationForm(UserCreationForm):
    bio = forms.CharField(widget=forms.Textarea(attrs={'rows': 3}), required=True)
    profile_picture = forms.FileField(required=True)

    class Meta:
        model = CustomUser
        fields = ['first_name', 'last_name', 'username', 'email', 'bio', 'profile_picture']

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        for field_name in self.fields:
            self.fields[field_name].help_text = ''


class CustomUserChangeForm(UserChangeForm):
    bio = forms.CharField(widget=forms.Textarea(attrs={'rows': 3}), required=False)
    profile_picture = forms.FileField(required=False)

    class Meta:
        model = CustomUser
        fields = ['first_name', 'last_name', 'email', 'bio', 'profile_picture']

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.fields.pop('password', None)
        self.fields.pop('username', None)

    def clean_username(self):
        return self.instance.username

she_codes_news/users/views.py
from django.urls import reverse_lazy
from django.views.generic.edit import CreateView
from django.contrib.auth.views import PasswordResetView
from django.contrib.messages.views import SuccessMessageMixin
from django.shortcuts import render, redirect
from django.contrib.auth.decorators import login_required
from .forms import CustomUserCreationForm, CustomUserChangeForm
from .models import UserProfile


class CreateAccountView(CreateView):
    form_class = CustomUserCreationForm
    success_url = reverse_lazy('login')
    template_name = 'users/createAccount.html'

    def form_valid(self, form):
        # Save the user object from the form
        user = form.save()

        # Check for form validation errors
        if form.errors:
            print(form.errors)

        # Return the super class's form_valid method
        return super().form_valid(form)


class ChangeAccountView(CreateView):
    form_class = CustomUserChangeForm
    success_url = reverse_lazy('profile')
    template_name = 'users/changeAccount.html'

    def form_valid(self, form):
        # Save the user object from the form
        user = form.save()

        # Get the bio and profile_picture from the form's cleaned data
        bio = form.cleaned_data.get('bio')
        profile_picture = form.cleaned_data.get('profile_picture')

        # Create the user profile with the bio and profile_picture
        UserProfile.objects.create(user=user, bio=bio, profile_picture=profile_picture)

        # Return the super class's form_valid method
        return super().form_valid(form)


class ResetPasswordView(SuccessMessageMixin, PasswordResetView):
    template_name = 'users/password_reset.html'
    email_template_name = 'users/password_reset_email.html'
    subject_template_name = 'users/password_reset_subject'
    success_message = "We've emailed you instructions for setting your password, " \
                        "if an account exists with the email you entered. You should receive them shortly." \
                        " If you don't receive an email, " \
                        "please make sure you've entered the address you registered with, and check your spam folder."
    success_url = reverse_lazy('users-home')


def register_view(request):
    if request.method == 'POST':
        form = CustomUserCreationForm(request.POST, request.FILES)
        if form.is_valid():
            form.save()
            return redirect('login')
    else:
        form = CustomUserCreationForm()
    return render(request, 'users/createAccount.html', {'form': form})

@login_required
def profile_view(request):
    user_profile = UserProfile.objects.get(user=request.user)
    if request.method == 'POST':
        form = CustomUserChangeForm(request.POST, request.FILES, instance=request.user)
        if form.is_valid():
            form.save()
            return redirect('profile')
    else:
        form = CustomUserChangeForm(instance=request.user)
    return render(request, 'users/profile.html', {'form': form, 'user_profile': user_profile})


@login_required
def change_account_view(request):
    if request.method == 'POST':
        form = CustomUserChangeForm(request.POST, request.FILES, instance=request.user)
        if form.is_valid():
            form.save()
            return redirect('profile')
    else:
        form = CustomUserChangeForm(instance=request.user)
    return render(request, 'users/change_account.html')

she_codes_news/users/templates/users/changeAccount.html
{% extends "base.html" %}
{% load static %}

{% block stylesheets %}
    <link rel="stylesheet" type="text/css" href="{% static 'user-styles.css'%}">
{% endblock %}

{% block content %}
    <h2>Update Profile</h2>
    <form method="post" enctype="multipart/form-data">
        {% csrf_token %}
        {{ form.as_p }}
        <button type="submit">Update Profile</button>
    </form>
{% endblock %}

she_codes_news/users/templates/users/createAccount.html
<!-- users/templates/users/createAccount.html -->
{% extends "base.html" %}
{% load static %}

{% block stylesheets %}
    <link rel="stylesheet" type="text/css" href="{% static 'user-styles.css'%}">
{% endblock %}

{% block content %}
<div class="create-account-form">
    <h2>Create Account</h2>
    <div id="create-account-form">
        <form method="post" enctype="multipart/form-data">
            {% csrf_token %}
            {{ form.as_p }}
            <button type="submit">Create Account</button>
        </form>
    </div>
{% endblock %}

she_codes_news/users/templates/users/password_reset.html
{% extends "base.html" %}
{% block content %}
    <div class="form-content my-3 p-3">
        <div class="container">
            <div class="row justify-content-center">
                <div class="col-lg-5">
                    <div class="card shadow-lg border-0 rounded-lg mt-0 mb-3">
                        <div class="card-header justify-content-center">
                            <div id="error_div"></div>
                            <h3 class="font-weight-light my-4 text-center">Forgot Password?</h3>
                        </div>
                        {% if form.errors %}
                            <div class="alert alert-danger alert-dismissible" role="alert">
                                <div id="form_errors">
                                    {% for key, value in form.errors.items %}
                                        <strong>{{ value }}</strong>
                                    {% endfor %}
                                </div>
                                <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                                    <span aria-hidden="true">&times;</span>
                                </button>
                            </div>
                        {% endif %}
                        <div class="card-body">
                            <form method="POST">
                                {% csrf_token %}
                                <div class="form-row">
                                    <div class="col-md-10 offset-md-1">
                                    <div class="form-group">
                                        <label class="small mb-1" for="id_email">Email</label>
                                        <input type="email" name="email"  class="form-control"
                                                autocomplete="email" maxlength="254" required id="id_email"
                                                placeholder="Enter email">
                                    </div>
                                </div>
                            </div>
                                <div class="form-row">
                                    <div class="col-md-10 offset-md-1">
                                        <div class="form-group mt-0 mb-1">
                                            <button type="submit" class="col-md-12 btn btn-dark">Submit
                                            </button>
                                        </div>
                                    </div>
                                </div>
                            </form>
                        </div>
                        <div class="card-footer text-center">
                            <div class="small">
                                <a href="{% url 'users-register' %}">Create A New Account</a><br><br>
                                <a href="{% url 'login' %}">Back To Login</a><br>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
{% endblock content %}

she_codes_news/users/templates/users/password_reset_complete.html
{% extends "base.html" %}
{% block content %}
    <div class="container my-3 p-3">
        <div class="row justify-content-center">
            <div class="col-lg-5">
                <div class="card shadow-lg border-0 rounded-lg mt-0 mb-3">
                    <div class="alert alert-info">
                        Your password has been set. You may go ahead and <a href="{% url 'login' %}">Login Here</a>
                    </div>
                </div>
            </div>
        </div>
    </div>
{% endblock content %}

she_codes_news/users/templates/users/password_reset_confirm.html
{% extends "base.html" %}

{% block title %} Password Reset {% endblock title%}

{% block content %}
    <div class="form-content my-3 p-3">
        <div class="container">
            <div class="row justify-content-center">
                <div class="col-lg-5">
                    {% if validlink %}
                        <div class="card shadow-lg border-0 rounded-lg mt-0 mb-3">
                            <div class="card-header justify-content-center">
                                <h3 class="font-weight-light my-4 text-center">Reset Your Password</h3>
                            </div>
                            {% if form.errors %}
                                <div class="alert alert-danger alert-dismissible" role="alert">
                                    <div id="form_errors">
                                        {% for key, value in form.errors.items %}
                                            <strong>{{ value }}</strong>
                                        {% endfor %}
                                    </div>
                                    <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                                        <span aria-hidden="true">&times;</span>
                                    </button>
                                </div>
                            {% endif %}

                            <div class="card-body">
                                <form method="POST">
                                    {% csrf_token %}
                                    <div class="form-row">
                                        <div class="col-md-10 offset-md-1">
                                            <div class="form-group">
                                                <label class="small mb-1" for="id_new_password1">New Password</label>
                                                <input type="password" name="new_password1" autocomplete="new-password"
                                                        class="form-control" required id="id_new_password1"
                                                        placeholder="Enter password"/>
                                                <span>
                                                </span>
                                            </div>
                                        </div>
                                    </div>
                                    <div class="form-row">
                                        <div class="col-md-10 offset-md-1">
                                            <div class="form-group">
                                                <label class="small mb-1" for="id_new_password2">New Password Confirmation</label>
                                                <input type="password" name="new_password2" autocomplete="new-password"
                                                        required id="id_new_password2" class="form-control"
                                                        placeholder="Confirm password"/>
                                            </div>
                                        </div>
                                    </div>
                                    <div class="form-row">
                                        <div class="col-md-10 offset-md-1">
                                            <div class="form-group mt-0 mb-1">
                                                <button type="submit" class="col-md-12 btn btn-dark" id="reset">Reset Password</button>
                                            </div>
                                        </div>
                                    </div>
                                </form>
                            </div>
                        </div>
                    {% else %}
                    <div class="alert alert-warning">
                        The password reset link was invalid, possibly because it has already been used.
                        Please request a new password reset.
                    </div>
                    {% endif %}
                </div>
            </div>
        </div>
    </div>
{% endblock content %}

she_codes_news/users/templates/users/password_reset_email.html
{% autoescape off %}
    To initiate the password reset process for your {{ user.email }} Django Registration/Login App Account,
    click the link below:

    {{ protocol }}://{{ domain }}{% url 'password_reset_confirm' uidb64=uid token=token %}

    If clicking the link above doesn't work, please copy and paste the URL in a new browser
    window instead.

    Sincerely,
    The Developer
{% endautoescape %}

she_codes_news/users/templates/users/profile.html
{% extends "base.html" %}
{% load static %}

{% block stylesheets %}
    <link rel="stylesheet" type="text/css" href="{% static 'user-styles.css'%}">
{% endblock %}

{% block content %}
    <!-- <h2>{{ user_profile.user.username }}'s Profile</h2> -->
    <h2>{{ user_profile.user.first_name }}'s Profile</h2>
    {% if user_profile.profile_picture %}
        <img src="{{ user_profile.profile_picture.url }}" alt="Profile Picture">
    {% endif %}
    <p>First Name: {{ user_profile.user.first_name }}</p>
    <p>Last Name: {{ user_profile.user.last_name }}</p>
    <p>Email: {{ user_profile.user.email }}</p>
    <p>{{ user_profile.bio }}</p>
    <br>
    <a href="{% url 'users:changeAccount' %}"><i><u>Update Profile</u></i></a>
{% endblock %}