she_codes_news/news/urls.py
from django.urls import path
from . import views

app_name = 'news'

urlpatterns = [
    path('', views.IndexView.as_view(), name='index'),
    path('<int:pk>/', views.StoryView.as_view(), name='story'),
    path('add-story/', views.AddStoryView.as_view(), name='newStory'),
    path('search/', views.search_results, name='search_results'),
]

she_codes_news/she_codes_news/urls.py
from django.contrib import admin
from django.urls import include, path

from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    path('news/', include('news.urls')),
    path('admin/', admin.site.urls),
    path('users/', include('users.urls')),
    path('users/', include('django.contrib.auth.urls')),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

she_codes_news/news/models.py
from django.db import models
from django.contrib.auth import get_user_model
from django.utils import timezone
from django.contrib.auth.models import User

class Tag(models.Model):
    name = models.CharField(max_length=50)

    def __str__(self):
        return self.name

class NewsStory(models.Model):
    title = models.CharField(max_length=200)
    author = models.ForeignKey(
        get_user_model(),
        on_delete=models.CASCADE
    )
    pub_date = models.DateTimeField()
    content = models.TextField()
    image = models.URLField(max_length=200, null=True)
    tags = models.ManyToManyField(Tag)

    @property
    def number_of_comments(self):
        return NewsComment.objects.filter(newsStory_connected=self).count()

class NewsComment(models.Model):
    newsStory_connected = models.ForeignKey(
        NewsStory, related_name='comments', on_delete=models.CASCADE)
    author = models.ForeignKey(
        get_user_model(),
        on_delete=models.CASCADE
    )
    content = models.TextField()
    date_posted = models.DateTimeField(default=timezone.now)

    def __str__(self):
        return str(self.author) + ', ' + self.newsStory_connected.title[:40]

she_codes_news/news/forms.py
# news/forms.py
from django import forms
from django.forms import ModelForm
from .models import NewsStory, NewsComment

class StoryForm(ModelForm):
    class Meta:        
        model = NewsStory        
        fields = ['title', 'pub_date', 'content', 'image']
        widgets = {
            'pub_date': forms.DateInput(
                format='%m/%d/%Y',
                attrs={
                    'class':'form-control',
                    'placeholder':'Select a date',
                    'type':'date'
                }
            ),
        }

class NewCommentForm(forms.ModelForm):
    class Meta:
        model = NewsComment
        fields = ['content']

she_codes_news/news/views.py
from django.views import generic
from django.urls import reverse_lazy
from django.shortcuts import render
from .forms import StoryForm, NewCommentForm
from .models import NewsStory, NewsComment, Tag
from django.db.models import Q


class IndexView(generic.ListView):
    template_name = 'news/index.html'
    context_object_name = "all_stories"

    def get_queryset(self):
        '''Return all news stories.'''
        return NewsStory.objects.all()

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['latest_stories'] = NewsStory.objects.order_by('-pub_date')[:4]
        return context


class StoryView(generic.DetailView):
    model = NewsStory
    template_name = 'news/story.html'
    context_object_name = 'story'

    def get_context_data(self, **kwargs):
        data = super().get_context_data(**kwargs)

        comments_connected = NewsComment.objects.filter(
            newsStory_connected=self.get_object()).order_by('-date_posted')
        data['comments'] = comments_connected
        if self.request.user.is_authenticated:
            data['comment_form'] = NewCommentForm(instance=self.request.user)

        return data
    
    def post(self, request, *args, **kwargs):
        new_comment = NewsComment(content=request.POST.get('content'),
                                    author=self.request.user,
                                    newsStory_connected=self.get_object())
        new_comment.save()
        return self.get(self, request, *args, **kwargs)


class AddStoryView(generic.CreateView):
    form_class = StoryForm
    context_object_name = 'storyform'
    template_name = 'news/createStory.html'
    success_url = reverse_lazy('news:index')

    def form_valid(self, form):
        form.instance.author = self.request.user
        return super().form_valid(form)


def search_results(request):
    if 'q' in request.GET:
        search_query = request.GET['q']
        search_results = NewsStory.objects.filter(
            Q(title__icontains=search_query) |  # Filter by title containing the search query
            Q(content__icontains=search_query) |  # Filter by content containing the search query
            Q(author__username__icontains=search_query) |  # Filter by author's username containing the search query
            Q(tags__name__icontains=search_query)  # Filter by tag names containing the search query
        ).distinct()

        context = {
            'search_query': search_query,
            'search_results': search_results
        }
        return render(request, 'news/search_results.html', context)

    return render(request, 'news/search_results.html')

she_codes_news/news/templates/news/createStory.html
{% extends "base.html" %}
{% load static %}

{% block stylesheets %}
    <link rel="stylesheet" type="text/css" href="{% static 'user-styles.css'%}">
{% endblock %}

{% block content %}
    <div class="create-story">
        <h2>Write A New Story</h2>
        <div id="create-story">
            <form action="" method="post">
                {% csrf_token %}
                {{ form.as_p }}
                <input id="button" type="submit" value="submit">
            </form>
        </div>
    </div>
{% endblock %}

she_codes_news/news/templates/news/index.html
{% extends "base.html" %}
{% load static %}

{% block stylesheets %}
    <link rel="stylesheet" type="text/css" href="{% static 'news/styles.css'%}">
{% endblock %}

{% block content %}
    <section id="top-section">
        <div class="searchbar-wrapper">
            <form method="GET" action="{% url 'news:search_results' %}">
                <div id="searchbar">
                    <input id="searchbar-input" type="text" name="q" placeholder="Search articles...">
                    <input id="button" type="submit" value="Search">
                </div>
            </form>
        </div>
        
        <div id="welcome_message">
            {% if request.user.is_authenticated %}
                <h2>Welcome Back {{ user.first_name }}!</h2>
            {% endif %}
        </div>
    </section>
    <br>
    <h2 id="heading-2">Latest News</h2>

    <div id="latest-stories">
        {% if latest_stories %}
            {% for story in latest_stories %}
            {% include "./storyCard.html" with story=story position=forloop.counter %}
            {% endfor %}
        {% else %}
            <p>No stories are available.</p>
        {% endif %}
    </div>

    <br>
    <h2 id="heading-2">All Stories</h2>
    <div id="all-stories">
        {% if latest_stories %}
            {% for story in all_stories %}
            {% include "./storyCard.html" with story=story %}
            {% endfor %}
        {% else %}
            <p>No stories are available.</p>
        {% endif %}
    </div>
{% endblock %}

she_codes_news/news/templates/news/search_results.html
{% extends "base.html" %}
{% load static %}

{% block stylesheets %}
    <link rel="stylesheet" type="text/css" href="{% static 'news/styles.css'%}">
{% endblock %}

{% block content %}
    <div id="search-results">
        <h3>Search Results</h3>
        <p>Showing search results for "{{ search_query }}"</p>
        {% for news_story in news_stories %}
        {% empty %}
            <p>No search results found.</p>
        {% endfor %}
    </div>
{% endblock %}

she_codes_news/news/templates/news/story.html
<!-- news/templates/news/story.html -->
{% extends "base.html" %}
{% load static %}

{% block stylesheets %}
    <link rel="stylesheet" type="text/css" href="{% static 'news/styles.css'%}">
{% endblock %}

{% block content %}
    <div id="story-wrapper">
        <h2>{{ story.title }}</h2>
        <h4>{{ story.author }}</h4>
        <div id="story-content">
            <img src="{{ story.image }}">
            {{ story.content|linebreaks }}
        </div>
    </div>

    <div id="comments_section">
        <h2 id="comments-heading">Leave your comment!</h2>
        {% if user.is_authenticated %}
            <form method="POST">
                {% csrf_token %}
                <div class="form-group">
                    {{ comment_form }}
                    <br>
                    <button id="comments-button" type="submit">Add comment</button>
                </div>
            </form>
        {% else %}
            <a href="{% url 'login' %}?next={{request.path}}">Log in to add a comment!</a>
            <br>
        {% endif %}

        {% if comments %}
            <strong id="comments-number">{{ object.number_of_comments }} Comment{{ object.number_of_comments|pluralize }}</strong>
            <hr>
            <ul>
            {% for comment in comments %}
                <li>           
                    <div>
                        <span>
                            <strong>{{ comment.author }} </strong>
                            <small>{{ comment.date_posted }}</small>
                        </span>
                        <p>
                            {{ comment.content|safe }}
                        </p>
                    </div>
                </li>
            {% endfor %}
            </ul>
        {% else %}
            <strong id="no-comments">No comments yet...</strong>
        {% endif %}
    </div>

{% endblock %}

she_codes_news/news/templates/news/storyCard.html
<div class="story-card" id="story-card-{{ position }}">
    <a href="{% url 'news:story' story.id %}">
        {% if position < 5 %}
            <img src="{{ story.image }}">
        {% else %}
            <img src="{{ story.image }}">
        {% endif %}
        <div class="story-card-text">
            <h3>{{ story.title }}</h3>
            <h4>{{ story.author }}</h4>
            <h4>{{ story.pub_date }}</h4>
        </div>
    </a>
</div>